In [ ]:
import pandas as pd

In [ ]:
data = {

'Age': ['Youth', 'Youth', 'Middle', 'Senior', 'Senior', 'Middle', 'Senior', 'Youth', 'Youth', 'Senior', 'Youth'],

'Income': ['High', 'High', 'High', 'Medium', 'Low', 'Low', 'Low', 'Medium', 'Low', 'Medium', 'Medium'],

'Student': ['No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'],

'Creditrating': ['Fair', 'Excellent', 'Fair', 'Fair', 'Fair', 'Excellent', 'Excellent', 'Fair', 'Fair', 'Fair', 'Excellent'],

'Buyscomputer': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes']

}

In [ ]:
df= pd.DataFrame(data)
df

       Age  Income Student Creditrating Buyscomputer
0    Youth    High      No         Fair           No
1    Youth    High      No    Excellent           No
2   Middle    High      No         Fair          Yes
3   Senior  Medium      No         Fair          Yes
4   Senior     Low     Yes         Fair          Yes
5   Middle     Low     Yes    Excellent           No
6   Senior     Low     Yes    Excellent          Yes
7    Youth  Medium      No         Fair           No
8    Youth     Low     Yes         Fair          Yes
9   Senior  Medium     Yes         Fair          Yes
10   Youth  Medium     Yes    Excellent          Yes

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoders ={}
for column in df.columns:
  le = LabelEncoder()
  df[column] = le.fit_transform(df[column])
  label_encoders [column] = le

In [ ]:
x = df.drop('Buyscomputer',axis=1)
y = df['Buyscomputer']

In [ ]:
x

    Age  Income  Student  Creditrating
0     2       0        0             1
1     2       0        0             0
2     0       0        0             1
3     1       2        0             1
4     1       1        1             1
5     0       1        1             0
6     1       1        1             0
7     2       2        0             1
8     2       1        1             1
9     1       2        1             1
10    2       2        1             0

In [ ]:
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
Name: Buyscomputer, dtype: int64

In [ ]:

from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x, y)

KNeighborsClassifier()

In [ ]:
print('now model is trained')

now model is trained

In [ ]:
new_data = pd.DataFrame({
    'Age':['Youth'],
    'Income':['Medium'],
    'Student':['Yes'],
    'Creditrating':['Fair']
})

In [ ]:
for col in new_data.columns:
  new_data[col] = label_encoders[col].transform(new_data[col])

In [ ]:
prediction = knn.predict(new_data)
prediction

array([1])

In [ ]:
from sklearn.preprocessing import LabelEncoder
buyscomputer_encoder = LabelEncoder()
buyscomputer_encoder.fit(data['Buyscomputer'])
final_result = buyscomputer_encoder.inverse_transform(prediction)

print(f"Predicted result: {final_result[0]}")

Predicted result: Yes

In [ ]:
print(f"""Predicted class (encoded): {prediction}

Please check the Buyscomputer to verify if it is correct.""")

print(f"""Predicted class (actual): {final_result[0]}

Please check the Buyscomputer to verify if it is correct.""")

Predicted class (encoded): [1]

Please check the Buyscomputer to verify if it is correct.
Predicted class (actual): Yes

Please check the Buyscomputer to verify if it is correct.